### ISSUE TITLE
java.io.NotSerializableException: ch.njol.skript.util.visual.VisualEffectType

### ISSUE THREAD

**Issue by JohnHeikens** [JohnHeikens/Axo#303]
[Skript] Severe Error:
[22:27:20] [Server thread/ERROR]: #!#! 
Something went horribly wrong with Skript.
This issue is NOT your fault! You probably can't fix it yourself, either.
It looks like you are using some plugin(s) that alter how Skript works (addons).
Here is full list of them:
skRayFall v1.9.27 (https://sk.rayfall.net/) skript-reflect v2.2.3 (https://github.com/TPGamesNL/skript-reflect) DiSky v4.0-beta4 WolvSK v1.7.2 SkBee v1.15.1 (https://github.
We could not identify which of those are specially related, so this might also be Skript issue.
You should try disabling those plugins one by one, trying to find which one causes it.
If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
In that case, you will be given instruction on how should you report it.
On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
Only if the author tells you to do so, report it to Skript's issue tracker.
[22:27:20] [Server thread/ERROR]: #!#! 
Stack trace:
java.io.NotSerializableException: ch.njol.skript.util.visual.VisualEffectType
    at Skript.jar//ch.njol.yggdrasil.YggdrasilOutputStream.writeGenericObject(YggdrasilOutputStream.java:174)
    at Skript.jar//ch.njol.yggdrasil.YggdrasilOutputStream.writeObject(YggdrasilOutputStream.java:249)
    at Skript.jar//ch.njol.yggdrasil.YggdrasilOutputStream.writeGenericObject(YggdrasilOutputStream.java:199)
    at Skript.jar//ch.njol.yggdrasil.YggdrasilOutputStream.writeObject(YggdrasilOutputStream.java:249)
    at Skript.jar//ch.njol.skript.registrations.Classes.serialize(Classes.java:724)
    at Skript.jar//ch.njol.skript.variables.Variables.serialize(Variables.java:548)
    at Skript.jar//ch.njol.skript.variables.Variables.serialize(Variables.java:542)
    at Skript.jar//ch.njol.skript.variables.Variables.saveVariableChange(Variables.java:552)
    at Skript.jar//ch.njol.skript.variables.Variables.setVariable(Variables.java:385)
    at Skript.jar//ch.njol.skript.variables.Variables.setVariable(Variables.java:376)
    at Skript.jar//ch.njol.skript.lang.Variable.setIndex(Variable.java:474)
    at Skript.jar//ch.njol.skript.lang.Variable.change(Variable.java:518)
    at Skript.jar//ch.njol.skript.effects.EffChange.execute(EffChange.java:282)
    at Skript.jar//ch.njol.skript.lang.Effect.run(Effect.java:50)
    at Skript.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
    at Skript.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
    at Skript.jar//ch.njol.skript.effects.Delay$1.run(Delay.java:109)
    at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
    at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
    at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1567)
    at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:490)
    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1483)
    at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1282)
    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
    at java.base/java.lang.Thread.run(Thread.java:833)
[22:27:20] [Server thread/ERROR]: #!#! 
Version Information:
  Skript: 2.6.3
    Flavor: skriptlang-github
    Date: 00:55:22.847925631
  Bukkit: 1.17.1-R0.1-SNAPSHOT
  Minecraft: 1.17.1
  Java: 17.0.1 (Java HotSpot(TM) 64-Bit Server VM 17.0.1+12-LTS-39)
  OS: Linux amd64 5.13.0-28-generic
[22:27:20] [Server thread/ERROR]: #!#! 
Server platform: Paper
[22:27:20] [Server thread/ERROR]: #!#! 
Current node: null
Current item: null
[22:27:20] [Server thread/ERROR]: #!#! 
Thread: Server thread
[22:27:20] [Server thread/ERROR]: #!#! 
Language: english
Link parse mode: DISABLED
[22:27:20] [Server thread/ERROR]: #!#! 
End of Error.
[22:27:20] [Server thread/ERROR]: #!#!

**Comment by JohnHeikens** [comment]
this keeps spamming in creative
