### ISSUE TITLE
fix double connections/severe lag bungeesk (skript reloading probably causes it)

### ISSUE THREAD

**Issue by JohnHeikens** [JohnHeikens/Axo#414]

**Comment by JohnHeikens** [comment]
trying if switching over to advised starting skript helps

**Comment by JohnHeikens** [comment]
severe lag is away, but we still get disconnected

**Comment by JohnHeikens** [comment]
lag is not away

**Comment by JohnHeikens** [comment]
23:52:56 [SEVERE] Exception in thread "Thread-991" 
23:52:56 [SEVERE] java.lang.OutOfMemoryError: Java heap space

23:52:56 [SEVERE] 	at java.base/java.lang.reflect.Array.newInstance(Array.java:78)

23:52:56 [SEVERE] 	at java.base/java.io.ObjectInputStream.readArray(ObjectInputStream.java:2106)

23:52:56 [SEVERE] 	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1730)

23:52:56 [SEVERE] 	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:514)

23:52:56 [SEVERE] 	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:472)

23:52:56 [SEVERE] 	at fr.zorg.bungeesk.bungee.packets.SocketServer.read(SocketServer.java:59)

23:52:56 [SEVERE] 	at fr.zorg.bungeesk.bungee.packets.SocketServer$$Lambda$2213/0x00000008013e6f08.run(Unknown Source)

23:52:56 [SEVERE] 	at java.base/java.lang.Thread.run(Thread.java:833)
